version: 2

on:
  pull_request:

updates:
  - package_ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target: master
  - package_ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    target: master
